### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by internalG** [NodeBB/nodebb-plugin-topic-ratings#1]
Last commit is too far. Is this still working with latest version?

**Comment by barisusakli** [comment]
Give it a try, let me know if it doesn't work. You need a theme that includes this partial https://github.com/NodeBB/nodebb-plugin-topic-ratings/blob/master/static/templates/partials/ratings.tpl

**Comment by barisusakli** [comment]
Works on 2.x 3.x
